app/views/followers/models.py
from app.extensions import db
from datetime import datetime


class Follow(db.Model):
    __tablename__ = 'follow'

    follower_id = db.Column(db.Integer, db.ForeignKey('users.id'), primary_key=True)
    followed_id = db.Column(db.Integer, db.ForeignKey('users.id'), primary_key=True)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)

    def __repr__(self) -> str:
        return f'follower_id: {self.follower_id}\nfollowed_id: {self.followed_id}'

# file:///home/george/Desktop/Flask_Web_Development_Developing.pdf 174

app/views/followers/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField


class EmptyForm(FlaskForm):
    submit = SubmitField('Submit')

app/followers/views.py
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import login_required, current_user
from .forms import EmptyForm
from app.auth.models import User
from app.extensions import db
from app.posts.models import Posts


followers = Blueprint('followers', __name__, template_folder='templates/followers')


@followers.route('/follow/<username>', methods=['POST'])
@login_required
def follow(username):
    form = EmptyForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=username).first()
        if user is None:
            flash('User {} not found.'.format(username))
            return redirect(url_for('post.list'))
        if user == current_user:
            flash('You cannot follow yourself!')
            return redirect(url_for('followers.user', username=username))
        current_user.follow(user)
        db.session.commit()
        flash('You are following {}!'.format(username))
        return redirect(url_for('followers.user', username=username))
    else:
        return redirect(url_for('post.list'))


@followers.route('/unfollow/<username>', methods=['POST'])
@login_required
def unfollow(username):
    form = EmptyForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=username).first()
        if user is None:
            flash('User {} not found.'.format(username))
            return redirect(url_for('post.index'))
        if user == current_user:
            flash('You cannot unfollow yourself!')
            return redirect(url_for('followers.user', username=username))
        current_user.unfollow(user)
        db.session.commit()
        flash('You are not following {}.'.format(username))
        return redirect(url_for('followers.user', username=username))
    else:
        return redirect(url_for('post.index'))


@followers.route('/user/<username>')
@login_required
def user(username):
    user = User.query.filter_by(username=username).first()
    form = EmptyForm()
    return render_template('user.html', user=user, form=form)


@followers.route('/<username>/posts')
@login_required
def user_posts(username):
    user = User.query.filter_by(username=username).first()
    return render_template('user_posts.html', posts=user.posts)


@followers.route('/followers/posts')
@login_required
def followed_posts():
    posts = current_user.followed_posts
    own = Posts.query.filter_by(poster_id=current_user.id)
    users_posts = posts.union(own).order_by(Posts.date_posted.desc()).all()
    return render_template('followed_posts.html', users_posts=users_posts)

app/posts/views.py
from flask import flash, url_for, redirect, render_template, Blueprint, jsonify, request
from flask_login import login_required, current_user
from .models import Posts, Comments, Like
from .forms import PostForm, SearchForm, CommentForm
from app.extensions import db


post_view = Blueprint('post', __name__, template_folder="templates/posts")


# view all posts
@post_view.route('/')
def list():

    page = request.args.get('page', 1, type=int)
    posts = Posts.query.order_by(Posts.date_posted.desc()).paginate(
        page, 1, False)

    like = Like.query.all()
    return render_template(
        'list.html',
        posts=posts,
        like=like)


# view one post # add  comments
@post_view.route('/posts/<int:id>', methods=['GET', 'POST'])
def post(id):
    form = CommentForm()
    post = Posts.query.get_or_404(id)
    comments = Comments.query.filter_by(post_id=post.id)\
        .order_by(Comments.date_posted.desc()).all()
    like = Like.query.filter_by(post_id=post.id).all()
    try:
        can_like = Like.query.filter_by(
            author=current_user.id,
            post_id=post.id).count() > 0
    except AttributeError:
        can_like = False

    if form.validate_on_submit():
        try:
            content = form.content.data
            new_comment = Comments(
                content=content,
                poster_id=current_user.id,
                post_id=post.id
            )

            db.session.add(new_comment)
            db.session.commit()
            flash('Comment has been added!', category='success')
            return redirect(url_for('post.post', id=post.id))
        except AttributeError:
            flash('Please Log In To Leave a Comment!', category='error')
    return render_template(
        'post.html',
        post=post,
        comments=comments,
        form=form,
        like=like,
        can_like=can_like
    )


# Add Post Page
@post_view.route('/add-post', methods=['GET', 'POST'])
@login_required
def add():
    form = PostForm()

    if form.validate_on_submit():
        post = Posts(
            title=form.title.data,
            content=form.content.data,
            poster_id=current_user.id
        )
        # Clear the Form
        form.title.data = ''
        form.content.data = ''
        # form.slug.data = ''

        # Add post data to database
        db.session.add(post)
        db.session.commit()
        # return a message
        flash('Blog Post Submitted Successfully!', category='success')
        return redirect(url_for('post.post', id=post.id))
    return render_template(
        'add_post.html',
        form=form
    )


# edit post
@post_view.route('/posts/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit(id):
    post = Posts.query.get_or_404(id)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        # post.slug = form.slug.data
        post.content = form.content.data
        # db.session.add(post)
        db.session.commit()
        flash('Post has been updated', category='success')
        return redirect(url_for('post.post', id=post.id))

    if current_user.id == post.poster_id:
        # if form.method is not post. bring post data from database
        form.title.data = post.title
        # form.slug.data = post.slug
        form.content.data = post.content
        return render_template(
            'edit.html',
            form=form,
            post=post
        )
    else:
        flash("You Aren`t Authorised To Edit This Post...", category='error')
        return redirect(url_for('post.list'))


# delete post
@post_view.route('/posts/delete/<int:id>')
def delete(id):

    post = Posts.query.get_or_404(id)
    if int(post.poster.id) == current_user.id:
        try:
            db.session.delete(post)
            db.session.commit()
            flash('Post has been deleted', category='success')
            return redirect(url_for('post.list'))
        except Exception as e:
            print(e)
            flash('there was a problem deleting a post', category='error')
    else:
        flash("You Aren`t Authorized To Delete That Post!", category='error')
        return redirect(url_for('post.list'))


@post_view.route('/post/<post_id>/comments/update/<comment_id>', methods=['POST', 'GET'])
def update_comment(comment_id, post_id):
    form = CommentForm()
    comment = Comments.query.get_or_404(comment_id)
    post = Posts.query.get_or_404(post_id)
    comments = Comments.query.filter_by(
        post_id=post.id).order_by(Comments.date_posted.desc()).all()
    like = Like.query.filter_by(post_id=post.id).all()

    if form.validate_on_submit():
        comment.content = form.content.data
        db.session.commit()
        flash('Comment has been added!', category='success')
        return redirect(url_for(
            'post.post',
            id=post.id))
    if current_user.id == comment.commenter.id:
        form.content.data = comment.content

    return render_template(
        'edit_comment.html',
        post=post,
        comments=comments,
        comment=comment,
        form=form,
        like=like
    )


@post_view.route('/delete/<post_id>/<comment_id>')
@login_required
def delete_comment(post_id, comment_id):
    comment = Comments.query.get_or_404(comment_id)
    if int(comment.commenter.id) == current_user.id:
        try:
            db.session.delete(comment)
            db.session.commit()
            flash("Comment has been deleted", category='success')
            return redirect(url_for('post.post', id=post_id))
        except Exception as e:
            print(e)
            flash('there was a problem deleting the comment', category='error')
    else:
        flash("You Aren`t Authorized To Delete That Comment!", category='error')
        return redirect(url_for('post.post', id=post_id))


@post_view.route('/posts/<id>/like')
@login_required
def like(id):
    # if request.method['POST']:
    post = Posts.query.get_or_404(id)
    like = Like.query.filter_by(
        author=current_user.id, post_id=id).first()

    if not post:
        return jsonify({'error': 'Post does not exist.'}, 400)
    elif like:
        db.session.delete(like)
        db.session.commit()
    else:
        like = Like(author=current_user.id, post_id=id)
        db.session.add(like)
        db.session.commit()
    return redirect(url_for('post.post', id=post.id))
    # return jsonify({"likes": len(post.likes),
    # "liked": current_user.id in map(lambda x: x.author, post.likes)})


@post_view.route('/post/<post_id>/comments/<id>/like')
def like_comment(post_id, id):
    comment = Comments.query.get_or_404(id)
    try:
        like = Like.query.filter_by(
        author=current_user.id, comment_id=id).first()
    except AttributeError:
        like = False

    if not comment:
        return jsonify({'error': 'Comment does not exist.'}, 400)
    elif like:
        db.session.delete(like)
        db.session.commit()
    else:
        try:
            like = Like(author=current_user.id, comment_id=id)
            db.session.add(like)
            db.session.commit()
        except AttributeError:
            flash("You Can`t Like Before Log In", category='error')
    return redirect(url_for('post.post', id=post_id))


@post_view.route('/search', methods=['POST'])
def search():
    form = SearchForm()
    posts = Posts.query
    if form.validate_on_submit():
        # Get data from submitted form
        post.searched = form.searched.data
        # Query the Database

        # posts_by_content = posts.filter(
        #     Posts.content.like('%' + post.searched + '%'))
        # posts_by_title = posts.filter(
        #     Posts.title.like('%' + post.searched + '%'))
        # posts_by_content = posts.order_by(Posts.title).all()
        # posts_by_title = posts.order_by(Posts.title).all()
        # return render_template(
        #     "search.html",
        #     form=form,
        #     searched=post.searched,
        #     posts_by_content=posts_by_content,
        #     posts_by_title = posts_by_title
        #     )
        posts = posts.filter(Posts.content.like('%' + post.searched + '%'))
        posts = posts.order_by(Posts.title).all()
        return render_template(
            "search.html",
            form=form,
            searched=post.searched,
            posts=posts
        )

app/views/followers/views.py
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import login_required, current_user
from .forms import EmptyForm
from app.views.auth.models import User
from app.extensions import db
from app.views.posts.models import Posts


followers = Blueprint('followers', __name__, template_folder='templates')


@followers.route('/follow/<username>', methods=['POST'])
@login_required
def follow(username):
    form = EmptyForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=username).first()
        if user is None:
            flash('User {} not found.'.format(username))
            return redirect(url_for('post.list'))
        if user == current_user:
            flash('You cannot follow yourself!')
            return redirect(url_for('followers.user', username=username))
        current_user.follow(user)
        db.session.commit()
        flash('You are following {}!'.format(username))
        return redirect(url_for('followers.user', username=username))
    else:
        return redirect(url_for('post.list'))


@followers.route('/unfollow/<username>', methods=['POST'])
@login_required
def unfollow(username):
    form = EmptyForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=username).first()
        if user is None:
            flash('User {} not found.'.format(username))
            return redirect(url_for('post.index'))
        if user == current_user:
            flash('You cannot unfollow yourself!')
            return redirect(url_for('followers.user', username=username))
        current_user.unfollow(user)
        db.session.commit()
        flash('You are not following {}.'.format(username))
        return redirect(url_for('followers.user', username=username))
    else:
        return redirect(url_for('post.index'))


@followers.route('/user/<username>')
@login_required
def user(username):
    user = User.query.filter_by(username=username).first()
    form = EmptyForm()
    if user:
        return render_template('followers/user.html', user=user, form=form)
    else:
        return redirect(url_for('auth.dashboard'))


@followers.route('/<username>/posts')
@login_required
def user_posts(username):
    user = User.query.filter_by(username=username).first()
    return render_template('followers/user_posts.html', posts=user.posts)


@followers.route('/followers/posts')
@login_required
def followed_posts():
    try:
        posts = current_user.followed_posts
        own = Posts.query.filter_by(poster_id=current_user.id)
        users_posts = posts.union(own).order_by(Posts.date_posted.desc()).all()
    except AttributeError:
        users_posts = Posts.query.order_by(Posts.date_posted.desc()).all()
    return render_template('followers/followed_posts.html', users_posts=users_posts)

app/templates/followers/followed_posts.html
{% extends 'base.html' %}

{% block head %}
<style>
    a {
    text-decoration: none;
}
</style>
{% endblock %}

{% block content %}
<br>
<h3>Your and Your Followers Posts...</h3>
<br>
{% for post in users_posts %}
<div class="shadow p-3 mb-5 bg-body rounded">
    <a href="{{ url_for('post.post', id=post.id ) }}"><h2>{{ post.title }}</h2></a>
    <small>
        By: <a href="{{ url_for('followers.user', username=post.poster.username) }}" >{{ post.poster.name }}</a> <br>
        Date Posted: {{ post.date_posted }} <br><br>
    </small>
    {{ post.content[:600]|safe }} <br>

    {#<a href="{{ url_for('post.like', id=post.id)}}">
        <img src="{{url_for('static',filename='uploads/like.png')}}" alt="like" height="18">
    </a>
    {{ like | selectattr("post.id","equalto","like.post_id") | list | count}} Likes}
    {% for l in like %}
        {% if post.id == l.post_id %}
            {{ like|count}}
        {% endif %}
    {% endfor #}


    <br>

    <a href="{{ url_for('post.post', id=post.id ) }}" class="btn btn-outline-secondary btn-sm">View Post</a>
    {% if post.poster_id == current_user.id %}
        <a href="{{ url_for('post.edit', id=post.id) }}" class="btn btn-outline-secondary btn-sm">Update</a>
        <a href="{{ url_for('post.delete', id=post.id) }}" class="btn btn-outline-danger btn-sm">Delete Post</a>
    {% endif %}
</div>
{% endfor %}


{% endblock %}

app/templates/followers/followers.html
{% extends 'base.html' %}

{% block head %}
<style>
    a {
    text-decoration: none;
}
</style>
{% endblock %}

{% block content %}
{% endblock %}

app/templates/followers/user.html
{% extends 'base.html' %}
{% block head %}
<style>
    a {
        text-decoration: none;
    }
</style>
{% endblock %}
{% block content %}
<br>
<div class="card">
    <div class="card-header">
        user profile
    </div>
    <div class="card-body">
        <p class="card-text">
        <div class="container">
            <div class="row">
                <div class="col-8">
                    <strong>Name: </strong>{{ user.name }}<br>
                    <strong>About Author: </strong>{{ user.about_author}}<br>
                    <br>
                    {% if user.about_author %}
                    <p>{{ user.about_author }}</p>
                    {% endif %}
                    {#<a href="{{url_for('followers.user_posts',username=user.username)}}">{{user.name}}`s Posts</a>
                    {{user.posts|length}}#}

                    <p>{{ user.followers.count() }} followers, {{ user.followed.count() }} following.

                        {% if current_user.is_authenticated and user != current_user and
                        user.is_following(current_user) %}
                        | <span class="label label-default">Follows you</span>
                        {% endif %}
                    </p>

                    {% if user == current_user %}
                    <p><a href="{{ url_for('auth.dashboard') }}">Edit your profile</a></p>
                    {% elif current_user.is_following(user) %}
                    <p>
                    <form action="{{ url_for('followers.unfollow', username=user.username) }}" method="post">
                        {{ form.hidden_tag() }}
                        {{ form.submit(value='Unfollow', class="btn btn-primary btn-sm") }}
                    </form>
                    </p>

                    {% else %}
                    <p>
                    <form action="{{ url_for('followers.follow', username=user.username) }}" method="post">
                        {{ form.hidden_tag() }}
                        {{ form.submit(value='Follow', class="btn btn-primary btn-sm") }}
                    </form>
                    </p>
                    {% endif %}

                </div>
                <div class="col-4">
                    {% if user.profile_pic %}
                    <img src="{{ url_for('static', filename='uploads/' + user.profile_pic)}}" alt="default_profile_pic"
                        height="150" align="right">
                    {% else %}
                    <img src="{{url_for('static',filename='uploads/default-profile-picture.jpeg')}}"
                        alt="default_profile_pic" height="150" align="right">
                    {% endif %}
                </div>

            </div>
        </div>
        </p>
        {#<a href="{{url_for('view.update1',id=user.id)}}" class="btn  btn-secondary btn-sm">Update Profile</a>

        #}
    </div>
</div>
{% endblock %}

app/templates/followers/user_posts.html
{% extends 'base.html' %}

{% block head%}
<style>
    a {
    text-decoration: none;
}
</style>
{% endblock %}

{% block content %}
<br>
<h3>Blog Posts...</h3>
<br>
{% for post in posts %}
<div class="shadow p-3 mb-5 bg-body rounded">
    <a href="{{ url_for('post.post', id=post.id ) }}"><h2>{{ post.title }}</h2></a>
    <small>
        By: <a href="{{ url_for('followers.user', username=post.poster.username) }}" >{{ post.poster.name }}</a> <br>
        Date Posted: {{ post.date_posted }} <br><br>
    </small>
    {{ post.content|safe }} <br>

    {#<a href="{{ url_for('post.like', id=post.id)}}">
        <img src="{{url_for('static',filename='uploads/like.png')}}" alt="like" height="18">
    </a>
    {{ like | selectattr("post.id","equalto","like.post_id") | list | count}} Likes}
    {% for l in like %}
        {% if post.id == l.post_id %}
            {{ like|count}}
        {% endif %}
    {% endfor #}


    <br>

    <a href="{{ url_for('post.post', id=post.id ) }}" class="btn btn-outline-secondary btn-sm">View Post</a>
    {% if post.poster_id == current_user.id %}
        <a href="{{ url_for('post.edit', id=post.id) }}" class="btn btn-outline-secondary btn-sm">Update</a>
        <a href="{{ url_for('post.delete', id=post.id) }}" class="btn btn-outline-danger btn-sm">Delete Post</a>
    {% endif %}
</div>

{% endfor %}

{% endblock %}