app/views/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length
from flask_ckeditor import CKEditorField


class PostForm(FlaskForm):
    title = StringField('Title', [DataRequired()])
    # content = StringField('Content',validators=[DataRequired()],widget=TextArea())
    content = CKEditorField('Content', [DataRequired()])
    submit = SubmitField('Submit')


# Create A Search Form
class SearchForm(FlaskForm):
    searched = StringField('Searched', [DataRequired()])
    submit = SubmitField('Submit')


class CommentForm(FlaskForm):
    content = TextAreaField('Comment', [DataRequired(), Length(min=5, max=500)])
    submit = SubmitField('Add Comment')

app/posts/views.py
from flask import flash, url_for, redirect, render_template, Blueprint, jsonify, request
from flask_login import login_required, current_user
from .models import Posts, Comments, Like
from .forms import PostForm, SearchForm, CommentForm
from app.extensions import db


post_view = Blueprint('post', __name__, template_folder="templates/posts")


# view all posts
@post_view.route('/')
def list():

    page = request.args.get('page', 1, type=int)
    posts = Posts.query.order_by(Posts.date_posted.desc()).paginate(
        page, 1, False)

    like = Like.query.all()
    return render_template(
        'list.html',
        posts=posts,
        like=like)


# view one post # add  comments
@post_view.route('/posts/<int:id>', methods=['GET', 'POST'])
def post(id):
    form = CommentForm()
    post = Posts.query.get_or_404(id)
    comments = Comments.query.filter_by(post_id=post.id)\
        .order_by(Comments.date_posted.desc()).all()
    like = Like.query.filter_by(post_id=post.id).all()
    try:
        can_like = Like.query.filter_by(
            author=current_user.id,
            post_id=post.id).count() > 0
    except AttributeError:
        can_like = False

    if form.validate_on_submit():
        try:
            content = form.content.data
            new_comment = Comments(
                content=content,
                poster_id=current_user.id,
                post_id=post.id
            )

            db.session.add(new_comment)
            db.session.commit()
            flash('Comment has been added!', category='success')
            return redirect(url_for('post.post', id=post.id))
        except AttributeError:
            flash('Please Log In To Leave a Comment!', category='error')
    return render_template(
        'post.html',
        post=post,
        comments=comments,
        form=form,
        like=like,
        can_like=can_like
    )


# Add Post Page
@post_view.route('/add-post', methods=['GET', 'POST'])
@login_required
def add():
    form = PostForm()

    if form.validate_on_submit():
        post = Posts(
            title=form.title.data,
            content=form.content.data,
            poster_id=current_user.id
        )
        # Clear the Form
        form.title.data = ''
        form.content.data = ''
        # form.slug.data = ''

        # Add post data to database
        db.session.add(post)
        db.session.commit()
        # return a message
        flash('Blog Post Submitted Successfully!', category='success')
        return redirect(url_for('post.post', id=post.id))
    return render_template(
        'add_post.html',
        form=form
    )


# edit post
@post_view.route('/posts/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit(id):
    post = Posts.query.get_or_404(id)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        # post.slug = form.slug.data
        post.content = form.content.data
        # db.session.add(post)
        db.session.commit()
        flash('Post has been updated', category='success')
        return redirect(url_for('post.post', id=post.id))

    if current_user.id == post.poster_id:
        # if form.method is not post. bring post data from database
        form.title.data = post.title
        # form.slug.data = post.slug
        form.content.data = post.content
        return render_template(
            'edit.html',
            form=form,
            post=post
        )
    else:
        flash("You Aren`t Authorised To Edit This Post...", category='error')
        return redirect(url_for('post.list'))


# delete post
@post_view.route('/posts/delete/<int:id>')
def delete(id):

    post = Posts.query.get_or_404(id)
    if int(post.poster.id) == current_user.id:
        try:
            db.session.delete(post)
            db.session.commit()
            flash('Post has been deleted', category='success')
            return redirect(url_for('post.list'))
        except Exception as e:
            print(e)
            flash('there was a problem deleting a post', category='error')
    else:
        flash("You Aren`t Authorized To Delete That Post!", category='error')
        return redirect(url_for('post.list'))


@post_view.route('/post/<post_id>/comments/update/<comment_id>', methods=['POST', 'GET'])
def update_comment(comment_id, post_id):
    form = CommentForm()
    comment = Comments.query.get_or_404(comment_id)
    post = Posts.query.get_or_404(post_id)
    comments = Comments.query.filter_by(
        post_id=post.id).order_by(Comments.date_posted.desc()).all()
    like = Like.query.filter_by(post_id=post.id).all()

    if form.validate_on_submit():
        comment.content = form.content.data
        db.session.commit()
        flash('Comment has been added!', category='success')
        return redirect(url_for(
            'post.post',
            id=post.id))
    if current_user.id == comment.commenter.id:
        form.content.data = comment.content

    return render_template(
        'edit_comment.html',
        post=post,
        comments=comments,
        comment=comment,
        form=form,
        like=like
    )


@post_view.route('/delete/<post_id>/<comment_id>')
@login_required
def delete_comment(post_id, comment_id):
    comment = Comments.query.get_or_404(comment_id)
    if int(comment.commenter.id) == current_user.id:
        try:
            db.session.delete(comment)
            db.session.commit()
            flash("Comment has been deleted", category='success')
            return redirect(url_for('post.post', id=post_id))
        except Exception as e:
            print(e)
            flash('there was a problem deleting the comment', category='error')
    else:
        flash("You Aren`t Authorized To Delete That Comment!", category='error')
        return redirect(url_for('post.post', id=post_id))


@post_view.route('/posts/<id>/like')
@login_required
def like(id):
    # if request.method['POST']:
    post = Posts.query.get_or_404(id)
    like = Like.query.filter_by(
        author=current_user.id, post_id=id).first()

    if not post:
        return jsonify({'error': 'Post does not exist.'}, 400)
    elif like:
        db.session.delete(like)
        db.session.commit()
    else:
        like = Like(author=current_user.id, post_id=id)
        db.session.add(like)
        db.session.commit()
    return redirect(url_for('post.post', id=post.id))
    # return jsonify({"likes": len(post.likes),
    # "liked": current_user.id in map(lambda x: x.author, post.likes)})


@post_view.route('/post/<post_id>/comments/<id>/like')
def like_comment(post_id, id):
    comment = Comments.query.get_or_404(id)
    try:
        like = Like.query.filter_by(
        author=current_user.id, comment_id=id).first()
    except AttributeError:
        like = False

    if not comment:
        return jsonify({'error': 'Comment does not exist.'}, 400)
    elif like:
        db.session.delete(like)
        db.session.commit()
    else:
        try:
            like = Like(author=current_user.id, comment_id=id)
            db.session.add(like)
            db.session.commit()
        except AttributeError:
            flash("You Can`t Like Before Log In", category='error')
    return redirect(url_for('post.post', id=post_id))


@post_view.route('/search', methods=['POST'])
def search():
    form = SearchForm()
    posts = Posts.query
    if form.validate_on_submit():
        # Get data from submitted form
        post.searched = form.searched.data
        # Query the Database

        # posts_by_content = posts.filter(
        #     Posts.content.like('%' + post.searched + '%'))
        # posts_by_title = posts.filter(
        #     Posts.title.like('%' + post.searched + '%'))
        # posts_by_content = posts.order_by(Posts.title).all()
        # posts_by_title = posts.order_by(Posts.title).all()
        # return render_template(
        #     "search.html",
        #     form=form,
        #     searched=post.searched,
        #     posts_by_content=posts_by_content,
        #     posts_by_title = posts_by_title
        #     )
        posts = posts.filter(Posts.content.like('%' + post.searched + '%'))
        posts = posts.order_by(Posts.title).all()
        return render_template(
            "search.html",
            form=form,
            searched=post.searched,
            posts=posts
        )

app/views/posts/views.py
from flask import flash, url_for, redirect, render_template, Blueprint, jsonify, request
from flask_login import login_required, current_user
from .models import Posts, Comments, Like
from .forms import PostForm, SearchForm, CommentForm
from app.extensions import db


post_view = Blueprint('post', __name__, template_folder="templates")


# Search
@post_view.app_context_processor
def base():
    searchform = SearchForm()
    return dict(searchform=searchform)


# view all posts
@post_view.route('/')
def list():

    page = request.args.get('page', 1, type=int)
    posts = Posts.query.order_by(Posts.date_posted.desc()).paginate(
        page=page, per_page=3)

    return render_template(
        'posts/list.html',
        posts=posts)


# view one post # add  comments
@post_view.route('/posts/<int:id>', methods=['GET', 'POST'])
def post(id):
    form = CommentForm()
    post = Posts.query.get_or_404(id)
    comments = Comments.query.filter_by(post_id=post.id)\
        .order_by(Comments.date_posted.desc()).all()
    like = Like.query.filter_by(post_id=post.id).all()
    try:
        can_like = Like.query.filter_by(
            author=current_user.id,
            post_id=post.id).count() == 0
        print("can_like")
    except AttributeError:
        can_like = False

    if form.validate_on_submit():
        try:
            content = form.content.data
            new_comment = Comments(
                content=content,
                poster_id=current_user.id,
                post_id=post.id
            )

            db.session.add(new_comment)
            db.session.commit()
            flash('Comment has been added!', category='success')
            return redirect(url_for('post.post', id=post.id))
        except AttributeError:
            flash('Please Log In To Leave a Comment!', category='error')
    return render_template(
        'posts/post.html',
        post=post,
        comments=comments,
        form=form,
        like=like,
        can_like=can_like
    )


# Add Post Page
@post_view.route('/add-post', methods=['GET', 'POST'])
@login_required
def add():
    form = PostForm()

    if form.validate_on_submit():
        post = Posts(
            title=form.title.data,
            content=form.content.data,
            poster_id=current_user.id
        )
        # Clear the Form
        form.title.data = ''
        form.content.data = ''
        # form.slug.data = ''

        # Add post data to database
        db.session.add(post)
        db.session.commit()
        # return a message
        flash('Blog Post Submitted Successfully!', category='success')
        return redirect(url_for('post.post', id=post.id))
    return render_template(
        'posts/add_post.html',
        form=form
    )


# edit post
@post_view.route('/posts/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit(id):
    post = Posts.query.get_or_404(id)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        # post.slug = form.slug.data
        post.content = form.content.data
        # db.session.add(post)
        db.session.commit()
        flash('Post has been updated', category='success')
        return redirect(url_for('post.post', id=post.id))

    if current_user.id == post.poster_id:
        # if form.method is not post. bring post data from database
        form.title.data = post.title
        # form.slug.data = post.slug
        form.content.data = post.content
        return render_template(
            'posts/edit.html',
            form=form,
            post=post
        )
    else:
        flash("You Aren`t Authorised To Edit This Post...", category='error')
        return redirect(url_for('post.list'))


# delete post
@post_view.route('/posts/delete/<int:id>')
def delete(id):

    post = Posts.query.get_or_404(id)
    if int(post.poster.id) == current_user.id:
        try:
            db.session.delete(post)
            db.session.commit()
            flash('Post has been deleted', category='success')
            return redirect(url_for('post.list'))
        except Exception as e:
            print(e)
            flash('there was a problem deleting a post', category='error')
    else:
        flash("You Aren`t Authorized To Delete That Post!", category='error')
        return redirect(url_for('post.list'))


@post_view.route('/post/<post_id>/comments/update/<comment_id>', methods=['POST', 'GET'])
def update_comment(comment_id, post_id):
    form = CommentForm()
    comment = Comments.query.get_or_404(comment_id)
    post = Posts.query.get_or_404(post_id)
    comments = Comments.query.filter_by(
        post_id=post.id).order_by(Comments.date_posted.desc()).all()
    like = Like.query.filter_by(post_id=post.id).all()

    if form.validate_on_submit():
        comment.content = form.content.data
        db.session.commit()
        flash('Comment has been added!', category='success')
        return redirect(url_for(
            'post.post',
            id=post.id))
    if current_user.id == comment.commenter.id:
        form.content.data = comment.content

    return render_template(
        'posts/edit_comment.html',
        post=post,
        comments=comments,
        comment=comment,
        form=form,
        like=like
    )


@post_view.route('/delete/<post_id>/<comment_id>')
@login_required
def delete_comment(post_id, comment_id):
    comment = Comments.query.get_or_404(comment_id)
    if int(comment.commenter.id) == current_user.id:
        try:
            db.session.delete(comment)
            db.session.commit()
            flash("Comment has been deleted", category='success')
            return redirect(url_for('post.post', id=post_id))
        except Exception as e:
            print(e)
            flash('there was a problem deleting the comment', category='error')
    else:
        flash("You Aren`t Authorized To Delete That Comment!", category='error')
        return redirect(url_for('post.post', id=post_id))


@post_view.route('/post/<post_id>/comments/<id>/like')
def like_comment(post_id, id):
    comment = Comments.query.get_or_404(id)
    try:
        like = Like.query.filter_by(
        author=current_user.id, comment_id=id).first()
    except AttributeError:
        like = False

    if not comment:
        return jsonify({'error': 'Comment does not exist.'}, 400)
    elif like:
        db.session.delete(like)
        db.session.commit()
    else:
        try:
            like = Like(author=current_user.id, comment_id=id)
            db.session.add(like)
            db.session.commit()
        except AttributeError:
            flash("You Can`t Like Before Log In", category='error')
    return redirect(url_for('post.post', id=post_id))


@post_view.route('/search', methods=['POST'])
def search():
    form = SearchForm()
    posts = Posts.query
    if form.validate_on_submit():
        # Get data from submitted form
        post.searched = form.searched.data
        # Query the Database

        # posts_by_content = posts.filter(
        #     Posts.content.like('%' + post.searched + '%'))
        # posts_by_title = posts.filter(
        #     Posts.title.like('%' + post.searched + '%'))
        # posts_by_content = posts.order_by(Posts.title).all()
        # posts_by_title = posts.order_by(Posts.title).all()
        # return render_template(
        #     "search.html",
        #     form=form,
        #     searched=post.searched,
        #     posts_by_content=posts_by_content,
        #     posts_by_title = posts_by_title
        #     )
        posts = posts.filter(Posts.content.like('%' + post.searched + '%'))
        posts = posts.order_by(Posts.title).all()
        return render_template(
            "posts/search.html",
            form=form,
            searched=post.searched,
            posts=posts
        )

app/templates/posts/add_post.html
{% extends 'base.html' %}

{% block content %}


{% if current_user.is_authenticated %}

<h1>Add Blog Post...</h1>
<br>
<div class="shadow p-3 mb-5 bg-body rounded">
    <form method="post">
        {{ form.hidden_tag() }}
        {{ form.title.label(class="form-label") }}
        {{ form.title(class="form-control") }}
        <br>
        {{ form.content.label(class="form-label") }}
        {{ form.content(class="form-control", rows="5") }}
        <br>
        {{ form.submit(class="btn  btn-outline-success") }}

    </form>

    {{ ckeditor.load() }}
    {{ ckeditor.config(name='content') }}

</div>
{% else %}
<h2>Must be Logged In...</h2>
<a href="{{ url_for('auth.login') }}">Login Here</a>

{% endif %}

{% endblock %}

app/templates/posts/edit_comment.html
{% extends 'base.html' %}

{% block content %}
<br>



<div class="shadow p-3 mb-5 bg-body rounded">
    <h2>{{ post.title }}</h2>
    <small>
        {# აქ უნდა დავამატო ლინკი, ავტორის გვერდზე რომელიც გადაგვიყვანს #}
        By: {{ post.poster.name }} <br>
        Date Posted: {{ post.date_posted }} <br><br>
    </small>

    {{ post.content|safe }} 
    <br>
    <a href="{{ url_for('post.like', id=post.id)}}">
        <img src="{{url_for('static',filename='uploads/like.png')}}" alt="like" title="Like Post" height="18">
    </a>{{ like|length }}  Likes 

    <br>
    <br><br>

    <h3>Comments {{ comments|length }}</h3>
    <br>
    <h7>Update {{comment.commenter.name}}`s comment</h7>
    <br>
    <br>
    <form method="post">
        {{ form.hidden_tag() }}

        {{ form.content(class="form-control") }}
        <br>
        <button class="btn btn-success btn-sm">Update Comment</button>
        
    </form>
    <br>

    {% for comment in comments %}
        {% if comment.post_id == post.id %}
        {% if comment.commenter.id != current_user.id %}
            {% if comment.commenter.name  %}
                <h6><span style="color:#29a329">{{ comment.commenter.name }}:</span></h4>
                <p>{{ comment.content }}</p>{{ comment.date_posted }}
                {% if comment.commenter.id == current_user.id %}

                {% endif %}
                <br>
                <br>
            {% else %}
                <p>  {{ comment.content }}</p>
            {% endif %}
        {% endif %}
        {% endif %}
    {% endfor %}

</div>

<a href="{{ url_for('post.list') }}" class="btn btn-outline-secondary btn-sm">Back To Blog</a>
{% if post.poster_id == current_user.id %}
    <a href="{{ url_for('post.edit', id=post.id) }}" class="btn btn-outline-secondary btn-sm">Update</a>
    <a href="{{ url_for('post.delete', id=post.id) }}" class="btn btn-outline-danger btn-sm">Delete Post</a>
{% endif %}

{% endblock %}

app/templates/posts/list.html
{% extends 'base.html' %}

{% block head %}
<style>
    a {
    text-decoration: none;
}
</style>
{% endblock %}

{% block content %}
<br>
<h3>Blog Posts...</h3>
<br>
{% for post in posts.items %}
<div class="shadow p-3 mb-5 bg-body rounded">
    <a href="{{ url_for('post.post', id=post.id ) }}"><h2>{{ post.title }}</h2></a>
    <small>
        By: <a href="{{ url_for('followers.user', username=post.poster.username) }}" >{{ post.poster.name }}</a> <br>
        Date Posted: {{ post.date_posted }} <br><br>
    </small>
    <p>{{ post.content[:600]|safe }}</p>
    {# TODO: displey short text instead of full article, maybe you can use fixed div #}
    {#<p>{{ post.content.splitlines()[:15] | join('\n') | safe }}...</p>
    <p>{{ article.content|truncate(5, True, "...") }}</p>#}

    {#<a href="{{ url_for('post.like', id=post.id)}}">
        <img src="{{url_for('static',filename='uploads/like.png')}}" alt="like" height="18">
    </a>
    {{ like | selectattr("post.id","equalto","like.post_id") | list | count}} Likes}
    {% for l in like %}
        {% if post.id == l.post_id %}
            {{ like|count}}
        {% endif %}
    {% endfor #}
    <br>
    <a href="{{ url_for('post.post', id=post.id ) }}" class="btn btn-outline-secondary btn-sm">Read More</a>
    {% if post.poster_id == current_user.id %}
        <a href="{{ url_for('post.edit', id=post.id) }}" class="btn btn-outline-secondary btn-sm">Update</a>
        <a href="{{ url_for('post.delete', id=post.id) }}" class="btn btn-outline-danger btn-sm">Delete Post</a>
    {% endif %}
</div>

{% endfor %}

<div class="pagination justify-content-center">
    {% if posts.has_prev %}
        <span>
            <a class='page-link' href="{{ url_for('post.list', page=posts.prev_num) }}">
                {{ '<<<' }}
            </a>
        </span>
    {% endif %}
    {% for number in posts.iter_pages() %}
        {% if posts.page != number %}
            <span>
                <a class='page-link' href="{{ url_for('post.list', page=number) }}">
                    {{ number }}
                </a>
            </span>
        {% else %}
            <span class="page-link current-page">{{ number }}</span>
        {% endif %}
    {% endfor %}
    {% if posts.has_next %}
        <span>
            <a class='page-link' href="{{ url_for('post.list', page=posts.next_num) }}">
                {{ '>>>' }}
            </a>
        </span>
    {% endif %}
</div>

{% endblock %}

app/templates/posts/post.html
{% extends 'base.html' %}

{% block head %}
<style>
    a {
    text-decoration: none;
}
</style>
{% endblock %}

{% block content %}
<br>

<div class="shadow p-3 mb-5 bg-body rounded">
    <h2>{{ post.title }}</h2>
    <small>
        By: <a href="{{ url_for('followers.user', username=post.poster.username) }}" >{{ post.poster.name }}</a> <br>
        Date Posted: <p type="datetime-local">{{ post.date_posted }}</p>  <br><br>
    </small>

    {{ post.content|safe }} 
    <br>
    <div class="like-div">
        <img src="{{url_for('static',filename='uploads/liked.png')}}"
              class="like-btn liked {% if can_like != True %}active{% endif %}"
              alt="liked"
              title="Unike Post"
              height="25">&nbsp;
        <img src="{{url_for('static',filename='uploads/like.png')}}"
             class="like-btn like {% if can_like == True %}active{% endif %}"
             alt="like"
             title="Like Post"
             height="28">
        <p id="like-count">&nbsp;{{ like|length }}  Likes</p>
    </div>
    <br>
    <br><br>

    <h3>Comments {{ comments|length }}</h3>
    <form method="post">
        {{ form.hidden_tag() }}

        {{ form.content(class="form-control",placeholder="Write a comment...") }}
        <br>
        {{ form.submit(class="btn btn-outline-success btn-sm")}}
    </form>
    <br>

    {% for comment in comments %}
        {% if comment.post_id == post.id %}
            {% if comment.commenter.name %}
                <h6><span style="color:#29a329">{{ comment.commenter.name }}:</span></h6>
                <p>{{ comment.content }}</p>{{ comment.date_posted }}
                {% if comment.commenter.id == current_user.id %}
                    <a href="{{ url_for('post.delete_comment', post_id=post.id, comment_id=comment.id) }}" title="Delete Comment">
                        <img src="{{url_for('static',filename='uploads/delete.png')}}" alt="delete icon" height="20" align="center">
                    </a>
                    <a href="{{url_for('post.update_comment',comment_id=comment.id,post_id=post.id)}}" class="btn btn-outline-secondary btn-sm">
                        Update
                    </a>
                {% endif %}
                <br>
                <br>
            {% else %}
                <p>  {{ comment.content }}</p>
            {% endif %}
        {% endif %}
        
        {% if comment.likes|length > 0 %}
                
            {% if current_user.is_authenticated %}
                {% if current_user.username in  comment.likes|string %}
                <p></p>
                        <a href="{{ url_for('post.like_comment',post_id=post.id, id=comment.id)}}">
                            <img src="{{url_for('static',filename='uploads/liked.png')}}" alt="liked" title="Like Comment" height="20">
                        </a>{{ comment.likes|length }}  Likes 
                    {% else %}
                        <a href="{{ url_for('post.like_comment',post_id=post.id, id=comment.id)}}">
                            <img src="{{url_for('static',filename='uploads/like.png')}}" alt="like" title="Like Comment" height="20">
                        </a>{{ comment.likes|length }}  Likes
                    {% endif %}
            {% else %}
                <a href="{{ url_for('post.like_comment',post_id=post.id, id=comment.id)}}">
                    <img src="{{url_for('static',filename='uploads/like.png')}}" alt="like" title="Like Comment" height="20">
                </a>{{ comment.likes|length }}  Likes
            {% endif %}
        {% else %}
            <a href="{{ url_for('post.like_comment',post_id=post.id, id=comment.id)}}">
                <img src="{{url_for('static',filename='uploads/like.png')}}" alt="like" title="Like Comment" height="20">
            </a>{{ comment.likes|length }}  Likes
        {% endif %}
        <br><br>
    {% endfor %}
</div>

<a href="{{ url_for('post.list') }}" class="btn btn-outline-secondary btn-sm">Back To Blog</a>
{% if post.poster_id == current_user.id %}
    <a href="{{ url_for('post.edit', id=post.id) }}" class="btn btn-outline-secondary btn-sm">Update</a>
    <a href="{{ url_for('post.delete', id=post.id) }}" class="btn btn-outline-danger btn-sm">Delete Post</a>
{% endif %}
{% endblock %}

{% block script %}
<script>
    let likeBtn = document.querySelector(".like-btn.like");
    let unlikeBtn = document.querySelector(".like-btn.liked");
    function likeHandler(){
        let data = {
            postId: {{post.id}},
            //userId: {{current_user.id}}
        };
        console.log(data);
        fetch('/api/posts/like', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(data)
        }).then(response => {
            console.log(response, response.status);
            if (response.ok){
                return response.json();
            }
        }).then(
            data => {
                console.log(data);
                document.querySelector("#like-count").innerHTML = `&nbsp;${data.like_count} Likes`
                if (data.message.includes('add like')){
                    likeBtn.style.display = 'none';
                    unlikeBtn.style.display = 'block';
                } else {
                    likeBtn.style.display = 'block';
                    unlikeBtn.style.display = 'none';
                }
            }
        )
    };
    likeBtn.addEventListener("click", likeHandler);
    unlikeBtn.addEventListener("click", likeHandler);

</script>
{% endblock %}

app/templates/posts/search.html
{% extends 'base.html' %}

{% block content %}
    <Br>
    </Br>
        <h2>You Searched For: <em>"{{ searched }}"</em></h2>
        <h3></h3>
        <br>
        {% if posts %}
            {% for post in posts %}
                <div class="shadow p-3 mb-5 bg-body rounded">
                    <a href="{{ url_for('post.post', id=post.id ) }}"><h2>{{ post.title }}</h2></a>
                    <small>
                        By: {{ post.poster.name }} <br>
                        Date Posted: {{ post.date_posted }} <br><br>
                    </small>
                    {{ post.content|safe }} <br>
                    <br>
                    <a href="{{ url_for('post.post', id=post.id ) }}" class="btn btn-outline-secondary btn-sm">View Post</a>
                    {% if post.poster_id == current_user.id %}
                        <a href="{{ url_for('post.edit', id=post.id) }}" class="btn btn-outline-secondary btn-sm">Update</a>
                        <a href="{{ url_for('post.delete', id=post.id) }}" class="btn btn-outline-danger btn-sm">Delete Post</a>
                    {% endif %}
                </div>
                <br>
            {% endfor %}
        {% else %}
            Sorry, your search term: <strong>"{{ searched }}"</strong> was not found...
        {% endif %}
{% endblock %}

app/templates/posts/search_not_works.html
{% extends 'base.html' %}

{% block content %}
    <Br>
    </Br>
        <h2>You Searched For: <em>"{{ searched }}"</em></h2>
        <h3></h3>
        <br>
        {% if posts_by_title or posts_by_content %}
            {% if posts_by_title %}
                {% for post in posts_by_title %}
                    <div class="shadow p-3 mb-5 bg-body rounded">
                        <a href="{{ url_for('post.post', id=post.id ) }}"><h2>{{ post.title }}</h2></a>
                        <small>
                            By: {{ post.poster.name }} <br>
                            Date Posted: {{ post.date_posted }} <br><br>
                        </small>
                        {{ post.content|safe }} <br>
                        <br>
                        <a href="{{ url_for('post.post', id=post.id ) }}" class="btn btn-outline-secondary btn-sm">View Post</a>
                        {% if post.poster_id == current_user.id %}
                            <a href="{{ url_for('post.edit', id=post.id) }}" class="btn btn-outline-secondary btn-sm">Update</a>
                            <a href="{{ url_for('post.delete', id=post.id) }}" class="btn btn-outline-danger btn-sm">Delete Post</a>
                        {% endif %}
                    </div>
                    <br>
                {% endfor %}
            {% endif %}

            {% if posts_by_content %}
                {% for post in posts_by_content %}
                <div class="shadow p-3 mb-5 bg-body rounded">
                    <a href="{{ url_for('post.post', id=post.id ) }}"><h2>{{ post.title }}</h2></a>
                    <small>
                        By: {{ post.poster.name }} <br>
                        Date Posted: {{ post.date_posted }} <br><br>
                    </small>
                    {{ post.content|safe }} <br>
                    <br>
                    <a href="{{ url_for('post.post', id=post.id ) }}" class="btn btn-outline-secondary btn-sm">View Post</a>
                    {% if post.poster_id == current_user.id %}
                        <a href="{{ url_for('post.edit', id=post.id) }}" class="btn btn-outline-secondary btn-sm">Update</a>
                        <a href="{{ url_for('post.delete', id=post.id) }}" class="btn btn-outline-danger btn-sm">Delete Post</a>
                    {% endif %}
                </div>
                <br>
                {% endfor %}
            {% endif %}
        {% else %}
            Sorry, your search term: <strong>"{{ searched }}"</strong> was not found...
        {% endif %}
{% endblock %}