app/followers/views.py
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import login_required, current_user
from .forms import EmptyForm
from app.auth.models import User
from app.extensions import db
from app.posts.models import Posts


followers = Blueprint('followers', __name__, template_folder='templates/followers')


@followers.route('/follow/<username>', methods=['POST'])
@login_required
def follow(username):
    form = EmptyForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=username).first()
        if user is None:
            flash('User {} not found.'.format(username))
            return redirect(url_for('post.list'))
        if user == current_user:
            flash('You cannot follow yourself!')
            return redirect(url_for('followers.user', username=username))
        current_user.follow(user)
        db.session.commit()
        flash('You are following {}!'.format(username))
        return redirect(url_for('followers.user', username=username))
    else:
        return redirect(url_for('post.list'))


@followers.route('/unfollow/<username>', methods=['POST'])
@login_required
def unfollow(username):
    form = EmptyForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=username).first()
        if user is None:
            flash('User {} not found.'.format(username))
            return redirect(url_for('post.index'))
        if user == current_user:
            flash('You cannot unfollow yourself!')
            return redirect(url_for('followers.user', username=username))
        current_user.unfollow(user)
        db.session.commit()
        flash('You are not following {}.'.format(username))
        return redirect(url_for('followers.user', username=username))
    else:
        return redirect(url_for('post.index'))


@followers.route('/user/<username>')
@login_required
def user(username):
    user = User.query.filter_by(username=username).first()
    form = EmptyForm()
    return render_template('user.html', user=user, form=form)


@followers.route('/<username>/posts')
@login_required
def user_posts(username):
    user = User.query.filter_by(username=username).first()
    return render_template('user_posts.html', posts=user.posts)


@followers.route('/followers/posts')
@login_required
def followed_posts():
    posts = current_user.followed_posts
    own = Posts.query.filter_by(poster_id=current_user.id)
    users_posts = posts.union(own).order_by(Posts.date_posted.desc()).all()
    return render_template('followed_posts.html', users_posts=users_posts)

app/posts/views.py
from flask import flash, url_for, redirect, render_template, Blueprint, jsonify, request
from flask_login import login_required, current_user
from .models import Posts, Comments, Like
from .forms import PostForm, SearchForm, CommentForm
from app.extensions import db


post_view = Blueprint('post', __name__, template_folder="templates/posts")


# view all posts
@post_view.route('/')
def list():

    page = request.args.get('page', 1, type=int)
    posts = Posts.query.order_by(Posts.date_posted.desc()).paginate(
        page, 1, False)

    like = Like.query.all()
    return render_template(
        'list.html',
        posts=posts,
        like=like)


# view one post # add  comments
@post_view.route('/posts/<int:id>', methods=['GET', 'POST'])
def post(id):
    form = CommentForm()
    post = Posts.query.get_or_404(id)
    comments = Comments.query.filter_by(post_id=post.id)\
        .order_by(Comments.date_posted.desc()).all()
    like = Like.query.filter_by(post_id=post.id).all()
    try:
        can_like = Like.query.filter_by(
            author=current_user.id,
            post_id=post.id).count() > 0
    except AttributeError:
        can_like = False

    if form.validate_on_submit():
        try:
            content = form.content.data
            new_comment = Comments(
                content=content,
                poster_id=current_user.id,
                post_id=post.id
            )

            db.session.add(new_comment)
            db.session.commit()
            flash('Comment has been added!', category='success')
            return redirect(url_for('post.post', id=post.id))
        except AttributeError:
            flash('Please Log In To Leave a Comment!', category='error')
    return render_template(
        'post.html',
        post=post,
        comments=comments,
        form=form,
        like=like,
        can_like=can_like
    )


# Add Post Page
@post_view.route('/add-post', methods=['GET', 'POST'])
@login_required
def add():
    form = PostForm()

    if form.validate_on_submit():
        post = Posts(
            title=form.title.data,
            content=form.content.data,
            poster_id=current_user.id
        )
        # Clear the Form
        form.title.data = ''
        form.content.data = ''
        # form.slug.data = ''

        # Add post data to database
        db.session.add(post)
        db.session.commit()
        # return a message
        flash('Blog Post Submitted Successfully!', category='success')
        return redirect(url_for('post.post', id=post.id))
    return render_template(
        'add_post.html',
        form=form
    )


# edit post
@post_view.route('/posts/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit(id):
    post = Posts.query.get_or_404(id)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        # post.slug = form.slug.data
        post.content = form.content.data
        # db.session.add(post)
        db.session.commit()
        flash('Post has been updated', category='success')
        return redirect(url_for('post.post', id=post.id))

    if current_user.id == post.poster_id:
        # if form.method is not post. bring post data from database
        form.title.data = post.title
        # form.slug.data = post.slug
        form.content.data = post.content
        return render_template(
            'edit.html',
            form=form,
            post=post
        )
    else:
        flash("You Aren`t Authorised To Edit This Post...", category='error')
        return redirect(url_for('post.list'))


# delete post
@post_view.route('/posts/delete/<int:id>')
def delete(id):

    post = Posts.query.get_or_404(id)
    if int(post.poster.id) == current_user.id:
        try:
            db.session.delete(post)
            db.session.commit()
            flash('Post has been deleted', category='success')
            return redirect(url_for('post.list'))
        except Exception as e:
            print(e)
            flash('there was a problem deleting a post', category='error')
    else:
        flash("You Aren`t Authorized To Delete That Post!", category='error')
        return redirect(url_for('post.list'))


@post_view.route('/post/<post_id>/comments/update/<comment_id>', methods=['POST', 'GET'])
def update_comment(comment_id, post_id):
    form = CommentForm()
    comment = Comments.query.get_or_404(comment_id)
    post = Posts.query.get_or_404(post_id)
    comments = Comments.query.filter_by(
        post_id=post.id).order_by(Comments.date_posted.desc()).all()
    like = Like.query.filter_by(post_id=post.id).all()

    if form.validate_on_submit():
        comment.content = form.content.data
        db.session.commit()
        flash('Comment has been added!', category='success')
        return redirect(url_for(
            'post.post',
            id=post.id))
    if current_user.id == comment.commenter.id:
        form.content.data = comment.content

    return render_template(
        'edit_comment.html',
        post=post,
        comments=comments,
        comment=comment,
        form=form,
        like=like
    )


@post_view.route('/delete/<post_id>/<comment_id>')
@login_required
def delete_comment(post_id, comment_id):
    comment = Comments.query.get_or_404(comment_id)
    if int(comment.commenter.id) == current_user.id:
        try:
            db.session.delete(comment)
            db.session.commit()
            flash("Comment has been deleted", category='success')
            return redirect(url_for('post.post', id=post_id))
        except Exception as e:
            print(e)
            flash('there was a problem deleting the comment', category='error')
    else:
        flash("You Aren`t Authorized To Delete That Comment!", category='error')
        return redirect(url_for('post.post', id=post_id))


@post_view.route('/posts/<id>/like')
@login_required
def like(id):
    # if request.method['POST']:
    post = Posts.query.get_or_404(id)
    like = Like.query.filter_by(
        author=current_user.id, post_id=id).first()

    if not post:
        return jsonify({'error': 'Post does not exist.'}, 400)
    elif like:
        db.session.delete(like)
        db.session.commit()
    else:
        like = Like(author=current_user.id, post_id=id)
        db.session.add(like)
        db.session.commit()
    return redirect(url_for('post.post', id=post.id))
    # return jsonify({"likes": len(post.likes),
    # "liked": current_user.id in map(lambda x: x.author, post.likes)})


@post_view.route('/post/<post_id>/comments/<id>/like')
def like_comment(post_id, id):
    comment = Comments.query.get_or_404(id)
    try:
        like = Like.query.filter_by(
        author=current_user.id, comment_id=id).first()
    except AttributeError:
        like = False

    if not comment:
        return jsonify({'error': 'Comment does not exist.'}, 400)
    elif like:
        db.session.delete(like)
        db.session.commit()
    else:
        try:
            like = Like(author=current_user.id, comment_id=id)
            db.session.add(like)
            db.session.commit()
        except AttributeError:
            flash("You Can`t Like Before Log In", category='error')
    return redirect(url_for('post.post', id=post_id))


@post_view.route('/search', methods=['POST'])
def search():
    form = SearchForm()
    posts = Posts.query
    if form.validate_on_submit():
        # Get data from submitted form
        post.searched = form.searched.data
        # Query the Database

        # posts_by_content = posts.filter(
        #     Posts.content.like('%' + post.searched + '%'))
        # posts_by_title = posts.filter(
        #     Posts.title.like('%' + post.searched + '%'))
        # posts_by_content = posts.order_by(Posts.title).all()
        # posts_by_title = posts.order_by(Posts.title).all()
        # return render_template(
        #     "search.html",
        #     form=form,
        #     searched=post.searched,
        #     posts_by_content=posts_by_content,
        #     posts_by_title = posts_by_title
        #     )
        posts = posts.filter(Posts.content.like('%' + post.searched + '%'))
        posts = posts.order_by(Posts.title).all()
        return render_template(
            "search.html",
            form=form,
            searched=post.searched,
            posts=posts
        )

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="{{url_for('static',filename='css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/main.css')}}">
    <title>Document</title>
    {% block head %}
    {% endblock %}
</head>
<body>
    {% include 'navbar.html' %}
    
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
            {% if category == 'error' %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button> 
                </div>
            {% else %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
            {% endfor %}
        {% endif %}
    {% endwith %}

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    {% block script %}
    {% endblock %}

    <script src="{{url_for('static', filename='js/main.js')}}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>

app/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <Br>
    </Br>
    <center>
        <h1>Home Page</h1>

    </center>
{% endblock %}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        {% if current_user.is_authenticated %}
            <a class="navbar-brand" href="{{url_for('followers.followed_posts')}}">Home</a>
            <a class="navbar-brand" href="{{url_for('post.list')}}">All Posts</a>
        {% else %}
            <a class="navbar-brand" href="{{url_for('post.list')}}">Home</a>
        {% endif %}
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{url_for('post.add')}}">Add Blog Post</a>
                </li>
                {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{url_for('auth.dashboard')}}">Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{url_for('auth.logout')}}">Logout</a>
                    </li>
                    {% if current_user.role == 'admin' %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/admin">Admin Panel</a>
                    </li>
                    {% endif %}
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{url_for('auth.register')}}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{url_for('auth.login')}}">Login</a>
                    </li>
                {% endif %}
            {#
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{url_for('post.list')}}">Posts</a>
                </li>#}
            
            </ul>
            <form method="POST" action="{{url_for('post.search')}}" class="d-flex" role="search">
                {{ searchform.hidden_tag() }}
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="searched" value placeholder required>
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>